---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-green
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-user
  namespace: rabbitmq-green
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
  #  echo <password> | openssl base64
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: admin
  namespace: rabbitmq-green
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: rabbitmq-cluster
  importCredentialsSecret:
    name: rabbitmq-user
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq-green
spec:
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  image: rabbitmq:3.13.1-management
  rabbitmq:
    additionalPlugins: [ "rabbitmq_federation", "rabbitmq_federation_management" ]
    additionalConfig: |
      cluster_formation.peer_discovery_backend             = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host                           = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type                   = hostname
      cluster_partition_handling                           = pause_minority
      queue_master_locator                                 = min-masters
      disk_free_limit.absolute                             = 2GB
      cluster_formation.randomized_startup_delay_range.min = 0
      cluster_formation.randomized_startup_delay_range.max = 60
      cluster_name                                         = rabbitmq
      collect_statistics_interval                          = 15000
      management_agent.disable_metrics_collector           = false
      management.rates_mode                                = basic
      management.disable_stats                             = false
      management.enable_queue_totals                       = true
      vm_memory_high_watermark.relative                    = 0.95
      classic_queue.default_version                        = 2